# Generated by Django 5.0.6 on 2024-06-14 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('roles', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(related_name='book_details', to='library_app.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.CharField(max_length=12)),
                ('count', models.IntegerField()),
                ('price', models.CharField(max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_records', to='library_app.bookdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueRecord',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('issued', 'issued'), ('overDueDate', 'overDueDate'), ('submittedOnTime', 'submittedOnTime'), ('submitAfterDueDate', 'submitAfterDueDate')], default='issued', max_length=20)),
                ('issue_date', models.CharField(max_length=20)),
                ('return_date', models.CharField(blank=True, max_length=20, null=True)),
                ('fine', models.CharField(blank=True, default='', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_records', to='library_app.bookdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_records', to='library_app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('line1', models.CharField(max_length=40)),
                ('line2', models.CharField(blank=True, default='', max_length=40)),
                ('profile', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='address', to='library_app.profile')),
            ],
        ),
    ]
