# Generated by Django 5.0.6 on 2024-06-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='profile',
            new_name='user',
        ),
    ]
