# Generated by Django 5.0.6 on 2024-06-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_rename_profile_address_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Horror', 'Horror'), ('Sci-fi', 'Sci-fi'), ('Thriller', 'Thriller'), ('Children', 'Children'), ('Mystery', 'Mystery')], default='Fiction', max_length=40),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='address', to='library_app.profile'),
        ),
    ]
