# Generated by Django 5.0.6 on 2024-06-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_category_bookrecord_category_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='authors',
            field=models.ManyToManyField(related_name='book_detail', to='library_app.author'),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Horror', 'Horror'), ('Sci-fi', 'Sci-fi'), ('Thriller', 'Thriller'), ('Children', 'Children'), ('Mystery', 'Mystery'), ('Biography', 'Biography')], default='Fiction', max_length=40),
        ),
    ]
