# Generated by Django 5.0.6 on 2024-06-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_bookdetail_authors_alter_bookrecord_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='authors',
            field=models.ManyToManyField(related_name='book_details', to='library_app.author'),
        ),
    ]
